# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cffafe39e1f0188b9ab7ce0652c77c91ee89589495a952b87a8497442cdd5ca90038b14cdf84e2ff56cfed13a4fa98935feed2a6d66ba770f64f40d88bf75c4d

test:
  secret_key_base: 61600672012a84b07d63c8debe54d5cd6a9a8b3ad2f43c9ece33fb5135d4079a5c929ef2cac3bbeebc71059daeccf4aac7e9d77abf17dd16759dc2af18711dbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
